config/routes.rb
Rails.application.routes.draw do

  devise_for :bartenders, skip: :registerable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get '/log_in', to: 'pages#sign_in'
  post '/bartenders/search', to: 'bartenders#search'
  get 'bartenders/:id/dashboard', to: 'bartenders#dashboard', as: 'bartender_dashboard'

  get '/bartenders/search', to: 'bartenders#search', as: "bartender_search"
  resources :bartenders, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update]
  end

  resources :parties, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
end

  patch 'parties/:id/confirm', to: 'parties#bartender_confirm', as: 'party_bartender_confirm'
  patch 'parties/:id/reject', to: 'parties#bartender_reject', as: 'party_bartender_reject'

  resources :messages, only: [:create]

end

app/models/bartender.rb
class Bartender < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  LANGUAGES = {
    'en' => 'English',
    'es' => 'Spanish',
    'pt' => 'Portuguese',
    'de' => 'German',
    'nl' => 'Dutch',
    'fr' => 'French'
  }

  has_many :parties
  has_many :users, through: :parties

  has_many :reviews
  has_many :cocktails, dependent: :destroy

end

app/controllers/bartender_controller.rb
class BartenderController < ApplicationController


  def index
    @bartender = Bartender.all
  end

  def show
  end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_bartender
      @bartender = Bartender.find(params[:id])
    end

end

app/controllers/bartenders_controller.rb
class BartendersController < ApplicationController
skip_before_action :authenticate_user!
before_action :set_bartender, only: [:show]

  def index
    @bartenders = Bartender.all

    if params[:party]
      @party          = Party.new(party_params)
      session[:party] = party_params
    else
      @party = Party.new(session[:party])
    end
  end

  def show
    attributes = Rack::Utils.parse_nested_query(params[:party])
    attributes["date"] = attributes["date"].to_date.strftime("%d/%m/%Y") if attributes["date"] != "" && attributes["date"]
    @party     = Party.new(attributes)
    @new_review = @bartender.reviews.build
    @review = Review.new
    p params
  end

  def search
    @bartenders = Bartender.all

    #Filter by Address
    location_query = params[:party][:city]
    unless location_query.nil?
      @bartenders = @bartenders.where("location ILIKE ?", "%#{location_query}%")
    end

    #Filter by Date Availability
    unless params[:party][:date] == ""
      non_available_ids = Bartender.joins(:parties).where("parties.date = ?", Date.parse(params[:party][:date])).pluck(:id)
      unless non_available_ids.empty?
        @bartenders = @bartenders.where("id NOT IN (?)", non_available_ids)
      end
    end

    if params[:party]
      @party          = Party.new(party_params)
      session[:party] = party_params
    else
      @party = Party.new(session[:party])
    end

    render :index
  end

  def dashboard
    @bartender = current_bartender
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bartender
    @bartender = Bartender.find(params[:id])
  end

  def party_params
    params.require(:party).permit(:address, :city, :date, :theme, :size)
  end

end

app/helpers/bartender_helper.rb
module BartenderHelper
end

app/views/bartenders/_search_form_index.html.erb
<%= simple_form_for @party, url: "/bartenders/search", method: :get do |f| %>
  <%= f.input :city, collection: Party::CITIES, label: false, prompt: 'Where?', wrapper_html: { class: '' }, input_html: { class: "input form-input-index" } %>


  <%= f.input :date, label: false, placeholder: 'When?', as: :string, input_html: { class: "datepicker" } %>

  <%= button_tag type: :submit, class: "btn-search", id: 'btn-search-index' do %>
    <i class="fa fa-search"></i>
  <% end %>

<% end %>

<!-- Autocomplete Google Form (removed)
<script type="text/javascript">

  function initialize() {

  var input = document.getElementById('party_address');
  var autocomplete = new google.maps.places.Autocomplete(input);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script> -->

app/views/bartenders/dashboard.html.erb
<h1><%= @bartender.title %></h1>

<%= @bartender.name %>

<br><br>
<div class='dashboard-wrapper'>
  <div class='dashboard-header'>
    <div class="row">
      <div class="col-xs-2">Type of Party</div>
      <div class="col-xs-2">Time and Date</div>
      <div class="col-xs-2">Address</div>
      <div class="col-xs-2">Number of Guests</div>
      <div class="col-xs-2">Price</div>
      <div class="col-xs-2">Confirmation Status</div>
    </div>
  </div>
  <div class="dashboard-body">
    <% @bartender.parties.order(:date).each do |party| %>
      <div>
        <div class='dashboard-bar'>
          <div class="row">
            <div class="col-xs-2"><%= party.theme %></div>
            <div class="col-xs-2">
              <%= pretty_time(party.start_time) %>,
              <%= party.date.to_s(:long) %>
            </div>
            <div class="col-xs-2"><%= pretty_address(party.address) %></div>
            <div class="col-xs-2"><%= pretty_size(party.size) %></div>
            <div class="col-xs-2"><%= pretty_price(party.price) %></div>
            <div class="col-xs-2">
              <div class="status-wrapper">
                <% if party.pending_bartender_confirmation? %>
                  <%= simple_form_for party, url: party_bartender_reject_path(party) do |f| %>
                    <%= button_tag type: :submit, class: 'icon' do %>
                      <i class="fa fa-times color-red" aria-hidden="true"></i>
                    <% end %>
                  <% end %>

                  <%= simple_form_for party, url: party_bartender_confirm_path(party) do |f| %>
                    <%= button_tag type: :submit, class: 'icon' do %>
                      <i class="fa fa-check color-green" aria-hidden="true"></i>
                    <% end %>
                  <% end %>

                <% elsif party.bartender_confirmed? %>
                  <p class='color-green'>Confirmed</p>
                <% else %>
                  <p class='color-red'>Rejected</p>
                <% end %>
              </div>

            </div>

          </div>
          <i class="fa fa-caret-down" aria-hidden="true"></i>
          <div class="party-reviews-wrapper">
            <ul>
              <h5>Reviews</h5>
              <% party.reviews.each_with_index do |review, i| %>
                <li class="<%= i.zero? ? 'first' : (i + 1 == party.reviews.size ? 'last' : 'std') %>">
                  <%= review.content %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bartenders/index.html.erb
<% content_for :title, "Top bartenders in #{@party.city}" %>


<div class="index-background">
  <div class="container">
    <div class="row">
      <%= render 'search_form_index'  %>
    </div>

    <div class="row">
      <% @bartenders.each_with_index do |bartender, i| %>
        <div class="col-xs-12 col-sm-6 col-lg-4">
          <div class="card-container">
            <%= link_to bartender_path(bartender, party: params[:party]), class: 'card' do %>
              <div class="card-body">
                <div class="card-image" style="background-image: url(<%= image_path (bartender.picture) %>);"></div>
                <div class="card-back">
                  <strong><u><%= bartender.title %></u></strong>
                  <% bartender.cocktails.each do |cocktail|  %>
                  <div class="card-back-item">
                    <%= image_tag cocktail.picture, class: 'smaller-avatar-cocktail' %>
                    <div><%= cocktail.name %></div>
                  </div>
                  <% end %>
                </div>
              </div>
              <div class="card-footer">
                <div class="card-footer-flex">
                  <div class="card-footer-name">
                    <strong> <%= "#{bartender.name}" %></strong>
                  </div>

                  <div class="card-footer-reviews">
                    <i class="fa fa-comment blacker"></i><%= bartender.reviews.count %>
                  </div>
                </div>
                <div class="card-footer-rating">
                  <% bartender.rating.times do %>
                  <i class="fa fa-glass golder" aria-hidden="true"></i>
                  <% end %>
                  <% (5 - bartender.rating).times do %>
                  <i class="fa fa-glass blacker" aria-hidden="true"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bartenders/show.html.erb
<%= content_for :navbar_transparent, "navbar-transparent" %>

<% content_for :meta_title, "#{@bartender.title} - #{@bartender.name}" %>
<% content_for :meta_description, "#{@bartender.bio}" %>
<% content_for :meta_image, "#{image_url @bartender.picture}" %>


<% if flash[:notice] %>
  <div class="alert-error"><%= flash[:notice] %></div>
<% end %>

  <% content_for :title, "#{@bartender.name} - #{@bartender.title}" %>

<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_url @bartender.bannerpicture %>);"></div>



<div class="container">
 <div class="wrapper-show">


  <div class="row">
    <!-- LEFT COLUMN -->
    <div class="col-md-8 profile-details">

      <!-- PROFILE -->
      <div class="row">
        <div class="col-xs-4">
          <%= image_tag @bartender.picture, class: 'avatar-largest', id: "cropped_avatar"%>
          <div class="col-xs-6 glasses-show text-center">
            <% @bartender.rating.times do %>
              <i class="fa fa-glass golder glass-big text-center" aria-hidden="true"></i>
            <% end %>

            <% (5 - @bartender.rating).times do %>
              <i class="fa fa-glass blacker glass-big" aria-hidden="true"></i>
            <% end %>
            <div>
              <a href="" id="reviews">Reviews (<%= @bartender.reviews.count %>)</a>
            </div>
          </div>
        </div>
        <div class="col-xs-6">
           <h1 class= ""> <%= @bartender.title %> </h1>
          <div class="row">
            <div class="col-xs-8">
              <p class= "bartender-info"> </i> <%= "#{@bartender.name}" %> </p>
              <p class= "bartender-info"> </i> <%= @bartender.location %> </p>
              <p class="bartender-info">
                Languages:
              <% @bartender.languages.split.each do |language| %>
                <%= image_tag "#{language}.png", size: "25x25" %>
              <% end %>
              </p>
            </div>
          </div>
          <br>
          <br>
        </div>
      </div>

      <!-- SPECIALTIES -->
      <div class=" profile-block specialities">
        <div class= "header">
          <h2>Top Cocktails</h2>
        </div>
        <div class= "content">
          <% @bartender.cocktails.each do |cocktail|  %>
          <div class="specialities-item">
            <%= image_tag cocktail.picture, class: 'avatar-cocktail' %>
            <div><%= cocktail.name %></div>
          </div>
          <% end %>
        </div>
      </div>



      <!-- BIO -->
      <div class="profile-block bio">
        <div class= "header">
          <h2>About</h2>
        </div>
        <div class= "content">
          <p class= ""> <%= @bartender.bio %> </p>
        </div>
      </div>



      <!-- REVIEWS -->
      <div class="profile-block reviews" id="review">
        <div class= "header">
          <h2>Reviews</h2>
        </div>
        <div class= "content">
          <% unless @bartender.reviews.map(&:content).all?(&:nil?)  %>
            <% @bartender.reviews.limit(5).each do |review| %>
              <%= render partial: 'bartenders/show/review', locals: {review: review} %>
            <% end %>

            <div class="reviews-expanded-list">
              <% @bartender.reviews.offset(5).each do |review| %>
                <%= render partial: 'bartenders/show/review', locals: {review: review} %>
              <% end %>
            </div>

            <button class="btn btn-expand" id="btn-expand-reviews"> Show more reviews</button>
          <% end %>

          <%#= render 'reviews/new' %>

        </div>
      </div>

    </div>

    <!-- RIGHT COLUMN -->
    <div class="col-md-3 col-md-offset-1 xs-hidden">
      <div class="slide-column" data-spy="affix" data-offset-top="219" data-offset-bottom="472">
        <div class="pricing">
          <h1>€50</h1>
          <h2>+</h2>
          <h3>€5 per cocktail</h3>
        </div>
        <div class="booking-basics">
          <h2> Book Your Bartender</h2>
          <%= render 'bartenders/show/form' %>
        </div>
      </div>
    </div>
  </div>

  </div>
</div>

<script>
  $('#reviews').click(function(e){
    e.preventDefault();
  $('#review')[0].scrollIntoView(true);
  });
</script>