config/routes.rb
Rails.application.routes.draw do

  devise_for :bartenders, skip: :registerable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get '/log_in', to: 'pages#sign_in'
  post '/bartenders/search', to: 'bartenders#search'
  get 'bartenders/:id/dashboard', to: 'bartenders#dashboard', as: 'bartender_dashboard'

  get '/bartenders/search', to: 'bartenders#search', as: "bartender_search"
  resources :bartenders, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update]
  end

  resources :parties, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
end

  patch 'parties/:id/confirm', to: 'parties#bartender_confirm', as: 'party_bartender_confirm'
  patch 'parties/:id/reject', to: 'parties#bartender_reject', as: 'party_bartender_reject'

  resources :messages, only: [:create]

end

app/models/party.rb
class Party < ApplicationRecord
  TYPES = ['Party', 'Birthday', 'Hen/Stag do', 'Leaving do', 'House Warming', 'Wedding']
  SIZES = ['5-29', '30-59', '60-90']
  CITIES = ['Amsterdam', 'Barcelona', 'Berlin', 'Copenhagen', 'Lisbon', 'London', 'Paris']
  belongs_to :user
  belongs_to :bartender
  has_many :messages, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :theme, inclusion: { in: TYPES }
  accepts_nested_attributes_for :user
  monetize :price_cents
  before_save :set_price, :set_payment_confirmed

  def bartender_confirmed?
    self.bartender_confirmed
  end

  def pending_bartender_confirmation?
    self.pending_bartender_confirmation
  end

  def payment_confirmed?
    self.bartender_confirmed
  end

  def bartender_confirm
    self.pending_bartender_confirmation  = false
    self.bartender_confirmed             = true
    Pusher.trigger('bartender-confirmation-channel', 'bartender-confirm', {
      message: 'confirmed'
    })
  end

  def bartender_reject
    self.pending_bartender_confirmation  = false
    self.bartender_confirmed             = false
  end

  def payment_confirm
    self.payment_confirmed = true
  end

  def send_text_to_bartender
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']

    client = Twilio::REST::Client.new account_sid, auth_token
    name = self.user.last_name == '' ? self.user.first_name : "#{self.user.first_name} #{self.user.last_name}"
    msg = self.message == '' ? '' : "\nPersonal message:\n#{self.message}"

    client.account.messages.create({
      from: '+4915735982115',
      to:   self.bartender.phone_number,
      body: "#{name} has booked a #{self.theme} scheduled for #{self.date.to_s(:long)}, in #{self.address}#{msg}"
    })
  end

  def send_text_to_user
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']

    client = Twilio::REST::Client.new account_sid, auth_token
    title = self.bartender.title
    bartender_name = self.bartender.name
    user_name = self.user.last_name == '' ? self.user.first_name : "#{self.user.first_name} #{self.user.last_name}"

    body = "Hello #{user_name},\n" \
           "Congratulations for booking your #{self.theme} through Superbarman!\n" \
           "You have booked #{title}, for #{self.date.to_s(:long)}, in #{self.address}."

    client.account.messages.create({
      from: '+4915735982115',
      to:   self.user.phone_number,
      body: body
    })
  end

  private

  def set_price
    self.price = Money.new(5000, 'EUR')
  end

  def set_payment_confirmed
    self.payment_confirmed
  end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:bartender_confirm, :bartender_reject]

  def create
    if params[:party]
      @party = Party.new(party_params)
      if session[:party]['theme']
        @party.theme = session[:party]['theme']
      end
    else
      @party = Party.new(session[:party])
    end
    @bartender = Bartender.find(params[:party]['bartender'].to_i)
    @party.bartender = @bartender
    @party.user = current_user
    @party.theme = 'Party' if @party.theme == ''

    if @party.save
      respond_to do |format|
        format.html { redirect_to new_party_payment_path(@party) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      redirect_to new_party_path(@party)
    end
  end

  def new
    if params[:party]
      @party = Party.new(party_params)
      if session[:party]['theme']
        @party.theme = session[:party]['theme']
      end
    else
      @party = Party.new(session[:party])
    end
    @bartender = Bartender.find(params[:party]['bartender'].to_i)
    @party.bartender = @bartender
    @party.user = current_user
    @bartender.parties.each do |party|
      if party.date == @party.date
        flash[:notice] = "Sorry, #{@bartender.name} has already an event on this date..."
       redirect_to bartender_path(@bartender)
      end
    end
  end

  def show
    @party = Party.find(params[:id])
  end

  def bartender_confirm
    party = Party.find(params[:id])
    party.bartender_confirm
    party.save!

    party.send_text_to_user

    redirect_to bartender_dashboard_path(party.bartender)
  end

  def bartender_reject
    party = Party.find(params[:id])
    party.bartender_reject
    party.save!
    redirect_to bartender_dashboard_path(party.bartender)
  end

  private

  def party_params
    params.require(:party).permit(:agreed, :date, :theme, :size, :address, :start_time, :zip_code, :city, :country, :message)
  end

  # Use callbacks to share common setup or constraints between actions.
end

app/helpers/parties_helper.rb
module PartiesHelper

  def pretty_size(size)
    size_parts = size.split('-')
    "#{size_parts.first} to #{size_parts.last}"
  end

  def pretty_time(start_time)
    hour = start_time.hour
    minute = start_time.min.to_s
    minute = '0' + minute if minute.length == 1
    "#{hour}:#{minute}"
  end

  def pretty_address(address)
    address_parts = address.split(',')
    "#{address_parts[0]}, #{address_parts[1]}"
  end

  def pretty_price(price)
    "#{price}€"
  end

end

app/views/parties/_new_form.html.erb
<%= simple_form_for @party, remote: true, html: { id: 'home-form-show' } do |f| %>
  <div class="col-md-6">
    <div class="slider-form">
        <div class="about-you">
          <h3>1. About you</h3>
          <%= f.simple_fields_for :user do |u| %>
            <%= u.input :first_name, label: false, required: true, placeholder: 'Name', wrapper_html: { class: '' }, input_html: { class: "about-you-block"} %>
           <%= u.input :last_name, label: false, required: true, placeholder: 'Surname', wrapper_html: { class: '' }, input_html: { class: "about-you-block"} %>
           <%= u.input :email, label: false, disabled: true, required: true, wrapper_html: { class: '' }, input_html: { class: "about-you-block"} %>
           <%= u.input :phone_number, label: false, required: true, placeholder: 'Contact Number', wrapper_html: { class: '' }, input_html: { class: "about-you-block"} %>
          <% end %>
        </div>
        <div class="about-your-party">
          <h3>2. About your party</h3>
          <div class="wrapper-date-time">
            <%= f.input :start_time, label: "At what time is your party?",as: :string, required: true, placeholder: '21:00',  input_html: { class: "about-your-party-time"} %>
              <%= f.input :date, label: false, disabled: true, as: :string, input_html: { class: "about-your-party-block"}%>
          </div>
          <%= f.input :address, label: "Where is your party?", placeholder: 'Address', required: true, input_html: { class: "about-your-party-block"} %>
          <%= f.input :zip_code, placeholder: 'Zip code', required: true, label: false, input_html: { class: "about-your-party-block"}  %>
          <%= f.input :city, placeholder: 'City', label: false, required: true, input_html: { class: "about-your-party-block"}  %>
          <%= f.input :country, prompt: 'Germany', label: false, required: true, priority: [ 'DE' ], input_html: { class: "about-your-party-block"}  %>
          <%= f.input :date, :as => :hidden, label: false, placeholder: '21:00', wrapper_html: { class: '' }, input_html: { class: "input form-input-index"} %>
          <%= f.input :theme, collection: Party::TYPES, as: :hidden, label: false, prompt: "Type of Party" %>

          <%= f.input :date, :as => :hidden, label: false, placeholder: '21:00'%>
          <%= f.input :bartender, :as => :hidden, label: false, input_html: { value: @bartender.id }%>
          <%= f.input :size, placeholder: 'Number of guests', label: false, required: true, input_html: { class: "about-your-party-block"} %>
          <%= f.input_field :agreed, as: :boolean, required: true %><span class="labelText"> I understand that Superbarman can only throw the perfect party if the number of guests is accurate.</span>

         <!--  <%#= f.input_field :agreed, required: true, as: :boolean, boolean_style: :inline %> <span class="labelText">The given number of guests is as accurate as I can provide to ensure a good bartender to guest ratio.</span> -->
         </div>
         <br>
        <div class= "bartender-message">
        <%= f.input :message, placeholder: 'I want a special mojito!', label: "Say hello to your bartender and provide more details about your party!", input_html: { class: "bartender-message-block"} %>
        <% #Insert Address auto-complete form here %>
        <div class="text-center">
          <%= button_tag type: :submit, class: "btn-booking-confirm" do %>
            Confirm and Pay
          <% end %>
        </div>
        </div>
    </div>
  </div>
  <div class="col-md-4 col-xs-offset-2">
    <div class="summary-wrapper booking-summary" data-spy="affix" data-offset-top="148" data-offset-bottom="450">
      <%= image_tag(@party.bartender.picture, style: "width: 100%;") %>
      <div class="bartender-name">
      Your bartender: <strong><%= @party.bartender.name %></strong>
      </div>
      <div class="bartender-title">
      <%= @party.bartender.title %>
      </div>
      <div class="bartender-location">
      <%= @party.bartender.location %>
      </div>
      <div class="bartender-rating">
         <% @bartender.rating.times do %>
            <i class="fa fa-glass golder" aria-hidden="true"></i>
          <% end %>
          <% (5 - @bartender.rating).times do %>
            <i class="fa fa-glass blacker" aria-hidden="true"></i>
          <% end %>
      </div>
      <hr class="booking-line">
      <div class="cocktails">
        <div class="content">
          <% @bartender.cocktails.each do |cocktail|  %>
            <div class="specialities-item">
              <%= image_tag cocktail.picture, class: 'small-avatar-cocktail-new' %>
            </div>
          <% end %>
        </div>
      </div>
      <hr class="booking-line">
      <div class="party-date">
      <% if @party.theme == "" %>
      <% @party.theme = "Party" %>
      <% end %>
      <%= pretty_date(@party.date) %> - <%= @party.theme %>
      </div>
      <br>
      <div class="booking-billing" class="pricing">
        <h3>  Bartender service: 50€</h3>
        <p><i>Includes 5 free welcome cocktails of your choice.</i></p>
        <br>
        <h6>Cocktails will be sold at 5€ during the event. </h6>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
            $('.about-your-party-time').timepicker(
              'setTime', '9:00 PM');
        </script>
    <script type="text/javascript">
     $(document).ready(function() {
  var flat_address = $('#party_address').get(0);
  if (flat_address) {
    var autocomplete = new google.maps.places.Autocomplete(flat_address, { types: ['geocode'] });
    google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
    google.maps.event.addDomListener(flat_address, 'keydown', function(e) {
      if (e.keyCode == 13) {
        e.preventDefault(); // Do not submit the form on Enter.
      }
    });
  }
});
function onPlaceChanged() {
  var place = this.getPlace();
  var components = getAddressComponents(place);
  $('#party_address').trigger('blur').val(components.address);
  $('#party_zip_code').val(components.zip_code);
  $('#party_city').val(components.city);
  if (components.country_code) {
    $('#party_country').val(components.country_code);
  }
}
function getAddressComponents(place) {
  // If you want lat/lng, you can look at:
  // - place.geometry.location.lat()
  // - place.geometry.location.lng()
  var street_number = null;
  var route = null;
  var zip_code = null;
  var city = null;
  var country_code = null;
  for (var i in place.address_components) {
    var component = place.address_components[i];
    for (var j in component.types) {
      var type = component.types[j];
      if (type == 'street_number') {
        street_number = component.long_name;
      } else if (type == 'route') {
        route = component.long_name;
      } else if (type == 'postal_code') {
        zip_code = component.long_name;
      } else if (type == 'locality') {
        city = component.long_name;
      } else if (type == 'country') {
        country_code = component.short_name;
      }
    }
  }
  return {
    address: street_number == null ? route : (street_number + ' ' + route),
    zip_code: zip_code,
    city: city,
    country_code: country_code
  };
}
    </script>

<script>

  var EVENTS = 'focusout keyup change';
  var EMAIL_PATTERN =/^([^\.@]+)(\.([^@]+))?@([^@]+)\.([^@]+)$/;
  var ZIP_CODE_PATTERN = /^\d{3,5} ?[a-zA-Z]*$/;
  var MOBILE_PHONE_PATTERN = /1?\W*([2-9][0-8][0-9])\W*([2-9][0-9]{2})\W*([0-9]{4})(\se?x?t?(\d*))?/;
  var NAME_PATTERN = /^([a-zA-z]+[,.]?[ ]?|[a-zA-z]+['-]?)+$/;


  function checkIsFilled(input, add_class) {
  var filled = false;
  if ($(input).attr('type') == "checkbox") {
    filled = $(input).is(':checked');
  } else if ($(input).is(':focus')) {
    filled = true;
  } else {
    filled = $(input).val().length > 0;
  }
  if (add_class) {
    addClass(input, filled);
  }
  return filled;
}
function checkZipCode(input) {
  var zip_code = $(input).val();
  addClass(input, zip_code.match(ZIP_CODE_PATTERN));
}
function checkEmail(input) {
  var email = $(input).val();
  addClass(input, email.match(EMAIL_PATTERN));
}
function checkMobilePhone(input) {
  var mobile_phone = $(input).val();
  addClass(input, mobile_phone.match(MOBILE_PHONE_PATTERN));
}
function checkFirstName(input) {
  var first_name = $(input).val();
  addClass(input, first_name.match(NAME_PATTERN));
}
function checkLastName(input) {
  var last_name = $(input).val();
  addClass(input, last_name.match(NAME_PATTERN));
}
function addClass(input, remove) {
  var button = $('button[type=submit]');

  var form_group = $(input).parents('.form-group');
  if (remove) {
    form_group.removeClass('has-error');
    if ($(input).val().length > 0) {

      form_group.addClass('has-success');
    }
  } else {

    form_group.addClass('has-error').removeClass('has-success');
  }
   activateButton();
}

function activateButton() {
  var button = $('button[type=submit]');
  if ($('.form-group.has-error').length >= 1) {
    var enable = false;
        button.attr('disabled', 'disabled').html('Please fill all fields');
      return;
  }
  else {
      button.removeAttr('disabled').html('Confirm and Pay');
       return;
    }
}
function onReady() {
  $('form input, form textarea').on(EVENTS, function(e) {
    if (e.target.id != 'zip_code' &&
        e.target.id != 'email' &&
        e.target.id != 'mobile_phone' &&
        e.target.id != 'first_name' &&
        e.target.id != 'last_name')
    {
      checkIsFilled(e.target, true);
    }
  });
  $('#party_zip_code').on(EVENTS, function(e) {
    checkZipCode(e.target);
    console.log("hey George");
  });
  $('#email').on(EVENTS, function(e) {
    checkEmail(e.target);
  });
  $('#party_user_attributes_phone_number').on(EVENTS, function(e) {
    checkMobilePhone(e.target);
  });
  $('#party_user_attributes_first_name').on(EVENTS, function(e) {
    checkFirstName(e.target);
  });
  $('#party_user_attributes_last_name').on(EVENTS, function(e) {
    checkLastName(e.target);
  });
}
$(document).ready(onReady);
</script>
<!-- <script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
    $('.slider-form').slick({
      dots: true,
      arrows: true
    });
  });
</script>
 -->

app/views/parties/create.js.erb
var handler = StripeCheckout.configure({
  key: "<%= j Rails.configuration.stripe[:publishable_key] %>",
  image: "<%= j image_path 'newlogo.png' %>",
  locale: 'auto',
  name: "Superbarman",
  description: "<%= j "#{@party.theme} - #{@party.date}"%>",
  amount: <%= @party.price_cents %>,
  currency: "<%= j @party.price.currency.to_s %>",
  email: "<%= j current_user.email %>",
  allowRememberMe: false,
  token: function(token) {
    console.log(token);
    $.post( "<%= j party_payments_path(@party) %>", { token: token }, function(){
      window.location.href = "<%= j party_path(@party) %>"
    });
  }
});

handler.open();

app/views/parties/new.html.erb
 <% content_for :title, "Hire a bartender for your party for only 50€ - Superbarman" %>

    <h1 class="title-new text-center">You're about to book <%= @bartender.name %>!</h1>
<div class="container">


  <div class="wrapper-prebook">

    <%= render "new_form" %>
  </div>
<!--
  <div class="wrapper-book">
    <%#= form_tag parties_path do %>
      <%#= hidden_field_tag 'party_id', @party.id %>
      <%#= submit_tag 'Purchase', class: 'btn-booking-confirm' %>
    <#% end %>
 -->


  </div>

</div>

<script src="https://checkout.stripe.com/checkout.js"></script>

app/views/parties/show.html.erb
<% content_for :title, "Payment confirmed - Booking number #{@party.bartender_id}#{@party.id}#{@party.user_id}" %>

<div class="wrapper-status-bar">
  <div class="container">
    <div class="row">
      <div class="status-bar">
        <div class="text-center status-bar-item <%= 'status-bar-item-active' if @party.pending_bartender_confirmation? %>">
          <%= image_tag "counterclockwise-rotation.png", size: "40x40" %>
          <p>Confirmation Pending</p>
        </div>
        <div class="text-center status-bar-item <%= 'status-bar-item-active' if @party.bartender_confirmed? %>">
          <%= image_tag "bart1.jpg", size: "40x40" %>
          <p>Party Confirmed</p>
        </div>
        <div class="text-center status-bar-item">
          <%= image_tag "cocktail2.png", size: "40x40" %>
          <p>Get your party started!</p>
        </div>
        <div class="text-center status-bar-item">
          <%= image_tag "check_1.png", size: "40x40" %>
          <p>Rate your Bartender</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-party-show-body">

  <div id="pending-bartender-confirmation" class="<%= 'hidden' unless @party.pending_bartender_confirmation? %>">
    <div class="pending-container">
      <div class="pending-card">

        <div class="banner-pending" style="background-image: linear-gradient(-225deg, rgba(85,85,85,0.9) 20%, rgba(60,60,60,0.8) 47%), url(<%= image_path 'ba.jpg' %>); ">
          <h2> Thanks for booking your <%= @party.theme %>! </h2>
          <p><i>Your booking number is: #<%= @party.bartender_id  %><%= @party.id %><%= @party.user_id%></i></p>
          <h4> We have sent your request to <i><%= @party.bartender.name %></i></h4>
          <h4>You will receive a response within the next <strong>24hr!</strong></h4>
        </div>
        <div class="pending-footer">
          <h2>The moment before memories are made</h2>
        </div>
      </div>
    </div>
  </div>

  <div id="bartender-confirmed" class="<%= 'hidden' unless @party.bartender_confirmed? %>">
    <div class="confirm-container">
      <div class="confirm-card">
        <div class="row">
            <div class="banner-book" style="background-image: linear-gradient(-225deg, rgba(85,85,85,0.9) 20%, rgba(60,60,60,0.8) 47%), url(<%= image_path 'pending1.jpg' %>); ">

              <h2> Congratulations! <br><%= @party.bartender.name %> has accepted your request</h2>

              <!-- <div class="background-div">
              <div class="text-center">
                <%= image_tag @party.bartender.picture, id:"bt-party-show"%>
                <h2><%= @party.bartender.name %></h2>
              </div>
              </div> -->
              <h4><span><%= @party.bartender.name %> will be at <i> <%= pretty_address(@party.address) %></i> at <i><%= pretty_time(@party.start_time) %></i></span></h4>
              <!-- <h3>In <%= @party.city %></h3> -->
              <h4>On <strong><%= @party.date.to_s(:long) %></strong> </h4>
              <h4>For your <%= (@party.theme).downcase %> with <%= @party.size %> guests! </h4>
            </div>
            <div class="confirm-footer">
              <h2>Let's get the party started</h2>
          </div>
        </div>
      </div>
      <br>
      <br>

      <%= link_to '#'  do %>
      <div class="add-friends-button text-center">
        <h5><i class="fa fa-facebook-square" aria-hidden="true"></i> INVITE YOUR FRIENDS ON FACEBOOK!</h5>
      </div>
      <% end %>
    </div>

  </div>

  <div id="party-started" class="hidden">
    <% # TBD %>
  </div>

  <div id="party-finished" class="hidden">
    <% # TBD %>
  </div>

</div>
<%= image_tag 'newlogo_checkout_new.png', id: 'bartender-logo-large' %>

<script src="https://js.pusher.com/4.0/pusher.min.js"></script>

<script>
  function changeActiveTabTo(i) {
    $('.status-bar-item').removeClass('status-bar-item-active');
    $('.status-bar-item').eq(i).addClass('status-bar-item-active');

    $('.wrapper-party-show-body').children().addClass('hidden');
    $('.wrapper-party-show-body').children().eq(i).removeClass('hidden');
  }

  $(document).ready(function() {
    <% if @party.pending_bartender_confirmation? %>
      changeActiveTabTo(0);
    <% elsif @party.bartender_confirmed? %>
      changeActiveTabTo(1);
    <% elsif true # We will add some logic later %>
      changeActiveTabTo(2);
    <% elsif true # We will add some logic later %>
      changeActiveTabTo(3);
    <% end %>

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher("<%= j ENV['PUSHER_KEY'] %>", {
      cluster: 'eu',
      encrypted: true
    });

    var channel = pusher.subscribe('bartender-confirmation-channel');
    channel.bind('bartender-confirm', function(data) {
      if(data.message === 'confirmed') {
        changeActiveTabTo(1);
        <% @party.pending_bartender_confirmation = false %>
      }
    });
  });
</script>