config/routes.rb
Rails.application.routes.draw do

  devise_for :bartenders, skip: :registerable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get '/log_in', to: 'pages#sign_in'
  post '/bartenders/search', to: 'bartenders#search'
  get 'bartenders/:id/dashboard', to: 'bartenders#dashboard', as: 'bartender_dashboard'

  get '/bartenders/search', to: 'bartenders#search', as: "bartender_search"
  resources :bartenders, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update]
  end

  resources :parties, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
end

  patch 'parties/:id/confirm', to: 'parties#bartender_confirm', as: 'party_bartender_confirm'
  patch 'parties/:id/reject', to: 'parties#bartender_reject', as: 'party_bartender_reject'

  resources :messages, only: [:create]

end

app/views/shared/_footer.html.erb
<footer class="footer-basic-centered">

  <div class="wrapper-logo-footer">
    <%= image_tag("newlogo_checkout_new.png", class: "logo-footer") %>
  </div>

  <p class="footer-links">
    <a href="#">Terms and Conditions</a>
    ·
    <a href="#">Social Responsibility</a>
    ·
    <a href="#">Privacy Policy</a>
    ·
    <a href="#">Drink Responsibly</a>
    ·
    <a href="#">Contact</a>
  </p>

  <ul class="list-inline contact-links">
    <li><a href=""><i class="fa fa-facebook-square contact"></i></a></li>
    <li><a href=""><i class="fa fa-twitter contact"></i></a></li>
    <li><a href=""><i class="fa fa-youtube-play contact"></i></a></li>
    <li><a href=""><i class="fa fa-instagram contact"></i></a></li>
  </ul>


  <div class= "copyright-notice">
    <p class="copyright-notice-text">SUPER BARMAN &copy; 2017  </p>
    <div class="payment-options">
    <ul class="list-inline">
      <li><%= image_tag("MasterCard.png", class: "footer-payment") %></li>
      <li><%= image_tag("Visa.png", class: "footer-payment") %></li>
      <li><%= image_tag("AmericanExpress.png", class: "footer-payment") %></li>
      <li><%= image_tag("PayPal.png", class: "footer-payment") %></li>
    </ul>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_transparent) %>">
  <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <div class="wrapper-logo">
        <div class="wrapper-logo-img">
          <%= image_tag "newlogo_checkout_new.png" %>
        </div>
        <p class="copyright-notice-text brand-name">SUPER BARMAN </p>
      </div>
    <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search for a Cocktail">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    -->

    <!-- how it works -->
    <%= link_to "#how-it-works", class: 'navbar-wagon-item navbar-wagon-link' do %>
      <%#= image_tag '18.png', class: 'frame' %>
      <p class='text-center no-margin'> How it works </p>
      <%#= image_tag '18_rev.png', class: 'frame' %>
    <% end %>

    <%= link_to "#", class: 'navbar-wagon-item navbar-wagon-link' do %>
      <%#= image_tag '18.png', class: 'frame' %>
      <p class='text-center no-margin'> My parties </p>
      <%#= image_tag '18_rev.png', class: 'frame' %>
    <% end %>


    <!-- Different navigation if login or not -->
    <% if user_signed_in? || bartender_signed_in? %>

      <!-- Notification -->

      <!-- Set picture -->
      <% picture = (user_signed_in? ? current_user.facebook_picture_url : current_bartender.picture) || "http://placehold.it/30x30" %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% avatar_url = picture %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to '/log_in', class: 'navbar-wagon-item navbar-wagon-link' do %>
        <%#= image_tag '18.png', class: 'frame' %>
          <p class='text-center no-margin'>
            <%= t(".sign_in", default: "Login") %>
          </p>
        <%#= image_tag '18_rev.png', class: 'frame' %>
      <% end %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="users/sign_in">Login</a></li>
        <li><a href="#">Messages</a></li>
        <li><a href="bartenders/search">Search bartenders</a></li>
      </ul>
    </div>
  </div>
</div>